name: simplify-debts
version: '0.1'
summary: Simple tool to simplify mutual debts
description: |
  In a group of people with debt between themselves, this program finds the
  absolutely necessary transactions to wipe away the debt.

apps:
  simplify-debts:
    command: simplify-debts
    plugs:
      - home
      - x11

grade: stable
confinement: strict

parts:
  simplify-debts:
    plugin: python
    python-version: python3
    source: https://github.com/ric2b/Mutual_Debt_Simplification.git
    source-branch: optionally_auto_open
    stage-packages:
      - graphviz
    install: |
      dot -c

  configuration:
    plugin: dump
    source: .
    prime:
      - bin/entrypoint.sh
